### ISSUE TITLE
Authorization Code flow + PKCE would be better..

### ISSUE THREAD

**Issue by stevehobbsdev** [devdennysegura/flutter-auth0#1]
Hi,

I've been having a look through this sample and the first thing that struck me was that the flow you've chosen to implement here is the [resource owner password grant](https://auth0.com/docs/api-auth/tutorials/password-grant). Unfortunately, it's not the best choice for client-side and native apps as it's mainly there to support highly-trusted applications ([this is a good read](https://www.scottbrady91.com/OAuth/Why-the-Resource-Owner-Password-Credentials-Grant-Type-is-not-Authentication-nor-Suitable-for-Modern-Applications) if you want to know more about the risks). Auth0 actually recommends against using the Password grant type for public applications when setting up an application inside the dashboard, so people are already put off from doing this.

For a plugin such as this, would it be possible to instead implement the [Authorization Code flow with PKCE](https://auth0.com/docs/api-auth/tutorials/authorization-code-grant-pkce), which is much more suitable for native applications?

I'm not a Flutter user at all but I've implemented something similar for Android. It basically comes down to opening a browser to hit the `/authorize` endpoint and then handling the callback which deep-links back into the running app. Not sure how that plays out in Flutter - is it possible?

**Comment by devdennysegura** [comment]
Hi @elkdanger 

Thanks for recommendation, just now the authorization code flow with PKCE was integrated on plugin.
