### ISSUE TITLE
WebAuth Error when using custom domain

### ISSUE THREAD

**Issue by KhoiNK** [devdennysegura/flutter-auth0#14]
I have configured my app following your instruction. When using web authorize I ran into a problem that the login page is always blank if I use any different accounts from my first setup. But when I changed it to my first setup account, my app ran correctly. I inspected my device I got this error.
**Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.**

**Comment by thebrianbug** [comment]
Looks like we're running into similar issues, did you ever get this resolved @KhoiNK?

https://github.com/devdennysegura/flutter-auth0/issues/15

**Comment by devdennysegura** [comment]
@KhoiNK try again with latest version, please!
