### ISSUE TITLE
Who's interested in maintaining this project?

### ISSUE THREAD

**Issue by thebrianbug** [devdennysegura/flutter-auth0#16]
First, I want to thank @devdennysegura for all the work put into this plugin. What an awesome gift to the community! As this project is no longer actively maintained, let's come up with a plan for moving this plugin forward.

@gregertw, @filoe, and quite a few others have forks of this repo. I believe we should take one of these forks as the new official home for this project. I believe it does a disservice to the hard work that Denny's already done to not come together and get this moving forward again as a community.

This project represents a significant step forward for the Flutter community. It's a key gateway project and having it will help the overall growth in the community. I would like to work towards getting this up to date and then released on flutter pub as mentioned here https://github.com/devdennysegura/flutter-auth0/issues/9.

I myself might be willing to help out in this effort, but I don't think I'm the right person to take over as sole maintainer. Would @gregertw, @filoe, or anyone else be willing to do this? Who's interested?

**Comment by thebrianbug** [comment]
After we come up with a plan here, I can try reaching out to Denny over email to officially transfer maintenance of the project if possible. If not, we'll just have to start running with a fork and use the issue section to direct traffic over to the actively maintained version.

**Comment by thebrianbug** [comment]
@flawless2011 see above

**Comment by filoe** [comment]
After getting stuck in lots of problems related to auth0, we made the decision to rollout our own identity service. In combination with that, we've moved to simple_auth which worked out quite well.

**Comment by gregertw** [comment]
@bmcilw1, thanks for your note and initiative. You are right, there is a substantial investment and good work put into this repo! 
I have tried to reach out to @devdennysegura a couple of times, also on email, but with no answer, but he did merge a PR from me earlier this Spring, so I'm not sure if he is just awfully busy or not interested :)
I'm happy to contribute, but I cannot be the sole maintainer. I think we need 2-3 with PR merge rights. I don't use this project beyond my own tinkering and I have a day job :)
My fork should be fairly up to date with @filoe's PRs as well, so happy to use that if we need to fork.
BTW, [here](https://medium.com/@gregertw/a-production-quality-flutter-starter-app-878801cb1d90?source=friends_link&sk=49d9a1b55da9fb325cccd6cf9f5fe6be) is a blog post on my use of the project

**Comment by thebrianbug** [comment]
For the benefit of those who are here looking for a production-ready auth solution for Flutter, I'm currently investigating leveraging just the Auth portion of Google Firebase, but with our own APIs and database. From what I'm seeing the pricing is comparable to that of Auth0 and it covers what we need for our use case. Personally, I prefer that to implementing an auth flow and password storage strategy in-house.

Backend: https://medium.com/@_josueperalta/using-firebase-auth-with-a-custom-node-js-server-part-1-53bdb622c89a and https://firebase.google.com/docs/auth/admin/#verify_id_tokens

Frontend: https://pub.dev/packages/firebase_auth and https://medium.com/flutterpub/flutter-how-to-do-user-login-with-firebase-a6af760b14d5

It's a shame to see this repo go unused, but we can't take over an unsupported and unmaintained integration for a 3rd party service if there are any reasonable alternatives.

**Comment by flawless2011** [comment]
I'm interested in being a contributor (not sole contributor).  I do think it'd be nice if we could investigate getting Auth0 to take over ownership even if we have a few community members helping to maintain the project.

**Comment by devdennysegura** [comment]
Hi, thank you all for the help with the repo, especially @gregertw, I have been a little busy, for that reason I have not been fully in the repo, this weekend I will be updating the entire repo, with the latest updates of flutter.
