### ISSUE TITLE
Mismatch in ios AppDelegate code after Flutter 1.0 release

### ISSUE THREAD

**Issue by gregertw** [devdennysegura/flutter-auth0#4]
Flutter 1.0 uses AppDelegate.swift and needs the following code:

`import flutter_auth0`

and within the AppDelegate class:
`  override func application(
    _ app: UIApplication,
    open url: URL,
    options: [UIApplicationOpenURLOptionsKey : Any] = [:]
  ) -> Bool {
    return FlutterAuth0Plugin.application(app, open:url, options:options)
  }`

**Comment by devdennysegura** [comment]
thanks @gregertw this change was merged from your fork

**Comment by MasterNeuromancer** [comment]
Hello,

I had the same problem and following the instructions above seemed to work. Unfortunately, now if I use the ios simulator it crashes if the user uses the pkce flow and exits the browser without login in. I get the following:

"PlatformException (PlatformException(Error, a0.session.user_cancelled, User cancelled the Auth))"

could you please advise??

also, is there a way to use the auth0 credentials manager with this package. I tried implementing it but I saw nothing in the documention. 

Thank you!
