### ISSUE TITLE
Pass back error_description

### ISSUE THREAD

**Issue by hiddenkirby** [devdennysegura/flutter-auth0#5]
Thanks for building this plugin, it made things a lot easier for me.

After i ingested your plugin into my app, I had some logic that showed a modal when the user put a bad password in or user didn't exist etc. 

One suggestion would be to allow for the passback of the error message from auth0.  Specifically error_description. 

`{error: invalid_grant, error_description: Wrong email or password.}` .

**Comment by devdennysegura** [comment]
Hi, @hiddenkirby thank for the recommendation, on latest version I do add handler errors.
