### ISSUE TITLE
Android not returning to app after successful login (using WebAuth)

### ISSUE THREAD

**Issue by gem85247** [devdennysegura/flutter-auth0#6]
In iOS it is working perfectly, not in android simulator though ...

**Comment by devdennysegura** [comment]
Hi @GillesMontyne.
Did you try to create "RedirectUriReceiver.java" file and add activity to manifest?

**Comment by gem85247** [comment]
Yes I did, do I need to show you some code (if so, which ones)?

**Comment by devdennysegura** [comment]
Can you try to use the example code and replace your-domain and your-client-id on main.dart file and android manifest?

**Comment by gem85247** [comment]
Hi I fixed it by using the following _launchmode_ in my **AndroidManifest.xml**:

`android:launchMode="singleTop"`

And this in my **RedirectUriReceiver.java**:


```
public class RedirectUriReceiver extends Activity {
    @Override
    public void onResume() {
        super.onResume();

        Intent intent = getIntent();
        Uri uri = intent.getData();

        /* ... */         

        this.finish();
    }
}
```

Thanks for your help (and writing this plugin), really appreciate your work!

**Comment by FredrikBakken** [comment]
Hi @GillesMontyne.
After experiencing the same issue as you did, I found an alternative solution. I noticed that the WebAuth page was not closed after pressing `q` in the terminal (to terminate the application).

Looking further into this problem, I found that the only thing necessary to change was the `openMainActivity.setFlags` in `RedirectUriReceiver.java`.

- From: `openMainActivity.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);`
- To: `openMainActivity.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);`

Everything else is kept according to the example.

**Comment by job-46** [comment]
Where do i have to put the RedirectUriReceiver.java in order to make it work? I can't find any docs on this on the internet :(
