### ISSUE TITLE
Project is not available on pub.dartlang.org

### ISSUE THREAD

**Issue by gregertw** [devdennysegura/flutter-auth0#9]
It would be nice to do a release of this project to make it downloadable package now that flutter 1.0 is out.

**Comment by thebrianbug** [comment]
This would be a great step forward @devdennysegura. Thanks for your great work!

**Comment by devdennysegura** [comment]
@gregertw I had not uploaded it because it gave me an error at the time, but now with more calm it is already resolved, you can see it at https://pub.dev/packages/flutter_auth0
